--- #YAML:1.0
name:               PDL-NetCDF
version:            4.10
abstract:           ~
author:
    - Douglas Hunt (dhunt@ucar.edu)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    PDL:  2.2
provides:
    PDL::NetCDF:
        file:     netcdf.pd
        version:  4.1
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
